services:
  - type: web
    name: zup-terminal-backend
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: METAAPI_TOKEN
        sync: false

